### ISSUE TITLE
Criar estrutura MVC para Player

### ISSUE THREAD

**Issue by MiguelCLG** [MiguelCLG/ReverseSnake#4]
Ficheiros a criar:
```
PlayerController.cs
PlayerView.cs
PlayerModel.cs
```

Comparar com a arquitetura que desenhamos e aplicar metodos que fazem sentido:

![Image](https://github.com/MiguelCLG/ReverseSnake/assets/32796673/167c3c1c-622d-4e06-a694-005e5bfdc56a)

Nota: queremos apenas a estrutura, a implementaçao podemos fazer depois.

**Comment by JLFFernandes** [comment]
vou tentar resolver este.
