### ISSUE TITLE
Criar estrutura MVC para Food

### ISSUE THREAD

**Issue by MiguelCLG** [MiguelCLG/ReverseSnake#7]
Ficheiros a criar:
```
FoodController.cs
FoodView.cs
FoodModel.cs
```

Comparar com a arquitetura que desenhamos e aplicar metodos que fazem sentido:

![Image](https://github.com/MiguelCLG/ReverseSnake/assets/32796673/167c3c1c-622d-4e06-a694-005e5bfdc56a)

Nota: queremos apenas a estrutura, a implementaçao podemos fazer depois.

**Comment by dirop1** [comment]
Vou fazer isto, assim que tiver um tempinho 👍
